name: flutter_scratch_area
description: A scratch area for building new Flutter ideas.
homepage: https://github.com/tmcmaster/flutter_scratch_area/blob/main/README.md
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  graphview: ^1.0.0-nullsafety.1
  flutter_riverpod:
  grouped_list: ^4.0.0

  widget_tester:
    git:
      url: https://github.com/tmcmaster/widget_tester.git
  screen_tester:
    git:
      url: https://github.com/tmcmaster/screen_tester.git
  theme_builder:
    git:
      url: https://github.com/tmcmaster/theme_builder.git
  flutter_workbench:
    git:
      url: https://github.com/tmcmaster/flutter_workbench.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
